[green_agent]
agentbeats_id = "019bbcd1-edb3-7352-a133-4e2471a7b3d1"
env = { GOOGLE_API_KEY = "${GOOGLE_API_KEY}" }

[[participants]]
agentbeats_id = "019bbc95-3273-7400-b85c-9cc4fccaf409"
name = "purple"
env = { GOOGLE_API_KEY = "${GOOGLE_API_KEY}" }

[config]
max_test_rounds = 5
targeted_per_weakness = 3
convergence_threshold = 0.05
